name: LuckyPanda
description: LuckyPandas!!!!
version: ${project.version}
api-version: 1.16
author: J3fftw/WalshyDev
main: dev.j3fftw.luckypanda.LuckyPanda

commands:
  lucky:
    description: Roll for a Surprise by running this command without killing an innocent panda. You monster..

permissions:
  luckypanda.admin:
    descripton: Use /lucky and it's subcommands
    default: false