name: LuckyPanda
description: LuckyPandas!!!!
version: 1.0
api-version: 1.14
author: J3fftw/WalshyDev
depend: [Slimefun]
main: dev.j3fftw.luckypanda.LuckyPanda

commands:
  lucky:
    description: Roll for a Surprise by running this command without killing an innocent panda. You monster..

permissions:
  lucky.*:
    description: Allows the use of the command /lucky along with all of it's variants
    default: op
    children:
      lucky.default: true
      lucky.select: true
  lucky.default:
    description: Allows the user to roll for a random surprise by using /lucky
  lucky.select:
    description: Allows the user to get a specific surprise via /lucky <Surprise ID>