name: LuckyPanda
description: LuckyPandas!!!!
version: 1.0
api-version: 1.14
author: J3fftw/WalshyDev
depend: [Slimefun]
main: dev.j3fftw.luckypanda.LuckyPanda

commands:
  lucky:
    description: Roll for a Surprise by running this command without killing an innocent panda. You monster..

permissions:
  luckypanda:
    descripton: Use /lucky and it's subcommands
    default: false